all project
fraaaaaaaaaanc/gofermart pull request #3
Opened 2023-11-28 11:30 UTC by fraaaaaaaaaanc

2023-11-29 18:42 UTC, kilchik requested changes

2023-11-29 18:42 UTC, kilchik commented on internal/workwithapi/order_accrual.go
> +	ticker := time.NewTicker(time.Second * 3)
Константы следует вынести в константы или конфиг

2023-11-29 18:42 UTC, kilchik commented on internal/workwithapi/order_accrual.go
> +		err = w.strg.UpdateBalance(usersOrdersAccrualList)
Что будет, если приложение завершится после вызова UpdateOrdersStatusAndAccrual, но до UpdateBalance? Как я понимаю, система останется в неконсистентном состоянии - статус обновлен, а баланс не изменен

2023-11-29 18:42 UTC, kilchik commented on internal/storage/storage_db/storage_init.go
> +	//err = goose.Up(db, migrationsDir)
Почему в итоге не через миграции?

2023-11-29 18:42 UTC, kilchik commented on internal/storage/storage_db/get_calculated_users.go
> +	rows, err := s.db.Query("SELECT user_id, accrual FROM order_accrual "+
Все запросы к БД должны быть с контекстом из запроса - иначе велика вероятность, что при временном подвисании запросов к БД клиентские соединения будут каскадно завершаться по таймауту, а соединения с БД будут продолжать висеть, пока новые клиентские соединения не приведут к достижению лимита по установленным соединениям, в результате чего сервис драматически деградирует

2023-12-06 11:49 UTC, fraaaaaaaaaanc commented
Я исправил все замечания оставленные выше, но я так и не смог включить миграции в свой проект, как только я вставляю код запускающий миграции, программа перестает проходить тесты на гите, код который я написал для миграций есть в функции storagegofermart.NewStorage, при чем локально все работает)

2023-12-07 16:41 UTC, kilchik approved these changes

2023-12-07 16:41 UTC, kilchik commented on cmd/gophermart/main.go
> +		panic(err)
log и os.Exit - не panic

2023-12-13 19:55 UTC, merged